#coding=utf-8
# Author: Ray, Jiarui Chen @ University of Macau
# Email: mb85409@um.edu.mo
# Time: 2021/2/26
# Part of ECG model tutorial @ Github: https://github.com/chen709847237/tutorial_ECG_model
# Sort the ground-truth label same order as data saved in the hdf5 file

import pandas as pd

label_file = '<Replace this string with the path of label csv file (generated by script_1)>'
check_idx_file = '<Replace this string with the path of order csv file (generated by script_5 XXX_order.csv)'
output_file_folder = '<Replace this string with the folder of the output ordered label csv file>'
output_file_name = '<Replace this string with the name of the output ordered label csv file>'

label_data = pd.read_csv(label_file)
check_idx = pd.read_csv(check_idx_file, index_col=0)
merge_data = pd.merge(check_idx, label_data, how='outer', on=['idx', 'idx'])
merge_data.rename({'name_x': 'name', 'name_y': 'name_check'}, inplace=True, axis='columns')
merge_data.to_csv(output_file_folder + output_file_name, encoding="utf_8_sig")


